### ISSUE TITLE
Create3 is not using the deployer parameter

### ISSUE THREAD

**Issue by jd1900** [flood-protocol/maldon#3]
For example running this command:`create3 --factory 0x0000000000000000000000000000000000000000 0x1122330000000000000000000000000000445566 0000`

Doesn't take into the account the deployer for the salt protection. Using create2 it works.
```    Finished release [optimized] target(s) in 0.05s
     Running `target/release/maldon create3 --factory 0x0000000000000000000000000000000000000000 0x1122330000000000000000000000000000445566 0000`
Found salt 0x6000000000000000000000000000085cb87b3d6583eff318ecb67ee947f1860c ==> 0x0000c3ceaabc1f0eefc4a0d70e05222ba8fc8d24
```

**Comment by spaceh3ad** [comment]
any updated on this?

**Comment by fcescob** [comment]
Sorry for the late reply, while the deployer is not explicitly in the salt like in CREATE2, the CREATE3 salt has deployer protection as well.
This is because the salt used by the factory is the hash of `msg.sender` and the salt produced by Maldon
```javascript
 function deploy(bytes32 salt, bytes memory creationCode)
        external
        payable
        override
        returns (address deployed)
    {
        // hash salt with the deployer address to give each deployer its own namespace
        salt = keccak256(abi.encodePacked(msg.sender, salt));
        return CREATE3.deploy(salt, creationCode, msg.value);
    }
 ```
